name: pc_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  redux: ^5.0.0
  redux_thunk: ^0.4.0
  redux_logging: ^0.5.0
  fluro: ^2.0.3
  flutter_screenutil: ^5.0.0+2
  dio: ^4.0.0
  fluttertoast: ^8.0.7
  shared_preferences: ^2.0.6
  json_serializable: ^4.1.3
  json_annotation: ^4.0.1
  build_runner: ^2.0.4
  flutter_easyrefresh: ^2.2.1
  date_format: ^2.0.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/-e3-bitmap.png
    - assets/A.png
    - assets/B.png
    - assets/Background_login.png
    - assets/C.png
    - assets/D.png
    - assets/E.png
    - assets/F.png
    - assets/G.png
    - assets/H.png
    - assets/I.png
    - assets/J.png
    - assets/K.png
    - assets/L.png
    - assets/M.png
    - assets/N.png
    - assets/O.png
    - assets/P.png
    - assets/Q.png
    - assets/R.png
    - assets/S.png
    - assets/T.png
    - assets/U.png
    - assets/V.png
    - assets/W.png
    - assets/X.png
    - assets/Y.png
    - assets/Z.png
    - assets/arrow-bottom.png
    - assets/arrow-unfold.png
    - assets/background_eng.png
    - assets/bg_state.png
    - assets/bg_vice_register_menber.png
    - assets/bg_wechat.png
    - assets/bt_cut(1).png
    - assets/bt_cut.png
    - assets/bt_increase(1).png
    - assets/bt_increase.png
    - assets/bt_nor_l.png
    - assets/bt_sel_l.png
    - assets/bt_settle_integral.png
    - assets/bt_settle_integral_select.png
    - assets/huiyuan_user.png
    - assets/icon__order_member.png
    - assets/icon__order_sell.png
    - assets/icon_activity 拷贝.png
    - assets/icon_activity(2).png
    - assets/icon_activity.png
    - assets/icon_alipay.png
    - assets/icon_aliplay.png
    - assets/icon_alltuihuo.png
    - assets/icon_alter.png
    - assets/icon_bank.png
    - assets/icon_baosun_reason.png
    - assets/icon_baosun_success.png
    - assets/icon_bianji.png
    - assets/icon_cashier.png
    - assets/icon_cashier_login_member .png
    - assets/icon_cashier_pitch.png
    - assets/icon_cashiershebei.png
    - assets/icon_cha.png
    - assets/icon_chuzhi.png
    - assets/icon_close.png
    - assets/icon_copy (1).png
    - assets/icon_copy .png
    - assets/icon_count.png
    - assets/icon_coupon.png
    - assets/icon_del.png
    - assets/icon_dell 拷贝.png
    - assets/icon_dian.png
    - assets/icon_diaochu.png
    - assets/icon_diaoru.png
    - assets/icon_ding_nopitch.png
    - assets/icon_ding_pitch.png
    - assets/icon_dingdanlaiyuan.png
    - assets/icon_expand_white.png
    - assets/icon_fail.png
    - assets/icon_gaijia.png
    - assets/icon_gantanhao.png
    - assets/icon_home_delete.png
    - assets/icon_huiyuan.png
    - assets/icon_import.png
    - assets/icon_index.png
    - assets/icon_integral.png
    - assets/icon_jiangxu.png
    - assets/icon_jiesuan.png
    - assets/icon_jifnehuiyuan.png
    - assets/icon_jizhang_ali.png
    - assets/icon_jizhang_card.png
    - assets/icon_jizhang_wechat.png
    - assets/icon_kuaidi_chaxun.png
    - assets/icon_kuaidi_daiqu.png
    - assets/icon_kuaidi_daiqu_l.png
    - assets/icon_kuaidi_hexiao_l.png
    - assets/icon_left.png
    - assets/icon_liebiao_nopitch.png
    - assets/icon_liebiao_pitch.png
    - assets/icon_lingdang.png
    - assets/icon_member .png
    - assets/icon_member_shibie_hi.png
    - assets/icon_member_vip.png
    - assets/icon_menu_cashier.png
    - assets/icon_menu_cashier_pitch.png
    - assets/icon_menu_commodity.png
    - assets/icon_menu_commodity_pitch.png
    - assets/icon_menu_kuaidi.png
    - assets/icon_menu_kuaidi_pitch.png
    - assets/icon_menu_member.png
    - assets/icon_menu_member_pitch.png
    - assets/icon_menu_more.png
    - assets/icon_menu_offline.png
    - assets/icon_menu_oline.png
    - assets/icon_menu_oline_weixuan.png
    - assets/icon_menu_order.png
    - assets/icon_menu_order_pitch.png
    - assets/icon_menu_purchase.png
    - assets/icon_menu_qjhx.png
    - assets/icon_menu_refresh.png
    - assets/icon_more_about(1).png
    - assets/icon_more_about(2).png
    - assets/icon_more_about.png
    - assets/icon_more_alipay.png
    - assets/icon_more_banci.png
    - assets/icon_more_bankcard.png
    - assets/icon_more_baosun.png
    - assets/icon_more_biaoqian.png
    - assets/icon_more_caigou.png
    - assets/icon_more_cash(3).png
    - assets/icon_more_cash.png
    - assets/icon_more_cashier .png
    - assets/icon_more_face.png
    - assets/icon_more_jiaojiebna.png
    - assets/icon_more_jilu.png
    - assets/icon_more_kucun.png
    - assets/icon_more_member.png
    - assets/icon_more_paihang.png
    - assets/icon_more_pandian.png
    - assets/icon_more_returns.png
    - assets/icon_more_sales.png
    - assets/icon_more_set.png
    - assets/icon_more_shift.png
    - assets/icon_more_shift_record.png
    - assets/icon_more_shop.png
    - assets/icon_more_shuju.png
    - assets/icon_more_tuihuo.png
    - assets/icon_more_unionpay.png
    - assets/icon_more_valuecard.png
    - assets/icon_more_wechat.png
    - assets/icon_more_xiugai.png
    - assets/icon_more_zizhu.png
    - assets/icon_more_zuhezhifu.png
    - assets/icon_moren_paixu.png
    - assets/icon_nan.png
    - assets/icon_nan_xuan.png
    - assets/icon_nvxing.png
    - assets/icon_nvxing_xuan.png
    - assets/icon_odd.png
    - assets/icon_order.png
    - assets/icon_order_add.png
    - assets/icon_order_destinateire.png
    - assets/icon_order_gongying.png
    - assets/icon_order_note(1).png
    - assets/icon_order_note.png
    - assets/icon_order_peisong.png
    - assets/icon_order_reason.png
    - assets/icon_order_time.png
    - assets/icon_order_yaohuo.png
    - assets/icon_paishe.png
    - assets/icon_paixu.png
    - assets/icon_pandian_fu.png
    - assets/icon_pandian_zheng.png
    - assets/icon_payment_failure 拷贝 3.png
    - assets/icon_payment_sel.png
    - assets/icon_peihuo.png
    - assets/icon_phone.png
    - assets/icon_pop_close.png
    - assets/icon_pop_line.png
    - assets/icon_print.png
    - assets/icon_prompt.png
    - assets/icon_qingkong.png
    - assets/icon_qjhx.png
    - assets/icon_renlianzhifu.png
    - assets/icon_return_price.png
    - assets/icon_return_shop.png
    - assets/icon_riqi.png
    - assets/icon_sales.png
    - assets/icon_saomaqiang(1).png
    - assets/icon_saomaqiang.png
    - assets/icon_scanning.png
    - assets/icon_settlement_fukuanma.png
    - assets/icon_settlement_jizhang.png
    - assets/icon_settlement_member.png
    - assets/icon_settlement_saoyisao.png
    - assets/icon_settlement_shualian.png
    - assets/icon_shaixuan.png
    - assets/icon_shouhuo_success.png
    - assets/icon_smzf.png
    - assets/icon_success.png
    - assets/icon_suo.png
    - assets/icon_sure.png
    - assets/icon_tan_huiyuan.png
    - assets/icon_time.png
    - assets/icon_tuihuo(1).png
    - assets/icon_tuihuo.png
    - assets/icon_tuihuo_dingdan.png
    - assets/icon_tuihuo_success.png
    - assets/icon_unionpay.png
    - assets/icon_update.png
    - assets/icon_user.png
    - assets/icon_value.png
    - assets/icon_wancheng.png
    - assets/icon_waybill_kjzt.png
    - assets/icon_waybill_kuaidi.png
    - assets/icon_waybill_phone.png
    - assets/icon_waybill_sbm.png
    - assets/icon_waybill_time.png
    - assets/icon_wechat.png
    - assets/icon_weixin.png
    - assets/icon_wenhao.png
    - assets/icon_xianjin.png
    - assets/icon_xiansheng0.png
    - assets/icon_xiaojie.png
    - assets/icon_xinzeng.png
    - assets/icon_xuanzhong(1).png
    - assets/icon_xuanzhong.png
    - assets/icon_yaohuo.png
    - assets/icon_yinhangka.png
    - assets/icon_yinlian.png
    - assets/icon_zhankai.png
    - assets/icon_zhifubao.png
    - assets/icon_zuhezhifu.png
    - assets/img_add_commodity.png
    - assets/img_alignment_scanner.png
    - assets/img_can_scan.png
    - assets/img_can_scan_s.png
    - assets/img_cancel.png
    - assets/img_checkbox_nol.png
    - assets/img_checkbox_sel.png
    - assets/img_commodity_update.png
    - assets/img_coupons.png
    - assets/img_coupons_no.png
    - assets/img_daiqujian.png
    - assets/img_default_image.png
    - assets/img_fahuo.png
    - assets/img_finish.png
    - assets/img_jiandang.png
    - assets/img_kuaidi.png
    - assets/img_kuaidi_yihexiao.png
    - assets/img_member_user.png
    - assets/img_mine.png
    - assets/img_money.png
    - assets/img_more_finish.png
    - assets/img_more_wait.png
    - assets/img_no_goods.png
    - assets/img_no_member.png
    - assets/img_no_order.png
    - assets/img_payment_chuzhika.png
    - assets/img_payment_renlian.png
    - assets/img_payment_saoma.png
    - assets/img_payment_shoukuan.png
    - assets/img_payment_success 拷贝 3(1).png
    - assets/img_payment_success 拷贝 3.png
    - assets/img_payment_yinhangka.png
    - assets/img_refund.png
    - assets/img_renlianzhifu_bg.png
    - assets/img_return.png
    - assets/img_saochuzhika.png
    - assets/img_shop.png
    - assets/img_show_code.png
    - assets/img_today_chenggong.png
    - assets/img_today_menber.png
    - assets/img_today_return.png
    - assets/img_today_sales.png
    - assets/img_today_tuihuo.png
    - assets/img_top.png
    - assets/img_tuikuan.png
    - assets/img_xuanze.png
    - assets/img_xzhy.png
    - assets/img_yihexiao.png
    - assets/img_yindaoye.png
    - assets/img_zhys.png
    - assets/lo_mima.png
    - assets/lo_user.png
    - assets/logn_logo .png
    - assets/logo_home .png
    - assets/logo_home_eng .png
    - assets/num_0.png
    - assets/num_00.png
    - assets/num_1.png
    - assets/num_2.png
    - assets/num_3.png
    - assets/num_4.png
    - assets/num_5.png
    - assets/num_6.png
    - assets/num_7.png
    - assets/num_8.png
    - assets/num_9.png
    - assets/num_del.png
    - assets/num_del_l.png
    - assets/pop_member_discount.png
    - assets/pop_member_not.png
    - assets/pop_user_member.png
    - assets/tag_daichuku.png
    - assets/tag_daipeihuo.png
    - assets/tag_daishenhe.png
    - assets/tag_daishouhuo.png
    - assets/tag_shouhuo.png
    - assets/txt_logo.png
    - assets/txt_register_member.png
    - assets/users_shop.png
    - assets/users_switch_shop.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
